language: python

python:
  - "2.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install gdal-bin libgdal1

install:
  - pip install -r requirements.txt --use-mirrors

script:
  - nosetests
