language: python

python:
  - "2.7"

before_install:
  - sudo apt-get update
  - apt-cache search gdal
  - sudo apt-get install gdal-bin libgdal

install:
  - pip install -r requirements.txt --use-mirrors

script:
  - nosetests
